name: SurvivalUtils
version: '1.5.0'
main: at.zDreamiii.survivalUtils.SurvivalUtils
api-version: '1.21'

commands:
  feed:
    description: Fills your hunger bar completely
    usage: /feed
    permission: survivalutils.feed
    permission-message: "§cYou do not have permission to use this command!"
  heal:
    description: Restores your health completely
    usage: /heal
    permission: survivalutils.heal
    permission-message: "§cYou do not have permission to use this command!"
  repair:
    description: Fully repairs your items
    usage: /repair
    permission: survivalutils.repair
    permission-message: "§cYou do not have permission to use this command!"
  gamemode:
    description: Change your game mode like before using numbers (or names)
    usage: /gamemode <0-3|name>
    permission: survivalutils.gamemode
    permission-message: "§cYou do not have permission to use this command!"
  craft:
    description: Opens a Crafting Table
    usage: /craft
    permission: survivalutils.workbench
    permission-message: "§cYou do not have permission to use this command!"
    aliases: [workbench]
  anvil:
    description: Opens an Anvil
    usage: /anvil
    permission: survivalutils.anvil
    permission-message: "§cYou do not have permission to use this command!"
  enderchest:
    description: Opens your Enderchest
    usage: /enderchest
    permission: survivalutils.enderchest
    permission-message: "§cYou do not have permission to use this command!"
    aliases: [ec]
  grindstone:
    description: Opens a Grindstone
    usage: /grindstone
    permission: survivalutils.grindstone
    permission-message: "§cYou do not have permission to use this command!"

permissions:
  survivalutils.*:
    description: Grants access to all SurvivalUtils commands
    default: op
    children:
      survivalutils.feed: true
      survivalutils.heal: true
      survivalutils.repair: true
      survivalutils.gamemode: true
      survivalutils.workbench: true
      survivalutils.anvil: true
      survivalutils.enderchest: true
      survivalutils.grindstone: true