name: SurvivalUtils
version: '1.1.2'
main: at.zDreamiii.survivalUtils.SurvivalUtils
api-version: '1.21'

commands:
  feed:
    description: Fills your hunger bar completely
    usage: /feed
    permission: survivalutils.feed
    permission-message: "§cYou do not have permission to use this command!"
  heal:
    description: Restores your health completely
    usage: /heal
    permission: survivalutils.heal
    permission-message: "§cYou do not have permission to use this command!"
  repair:
    description: Fully repairs your items
    usage: /repair
    permission: survivalutils.repair
    permission-message: "§cYou do not have permission to use this command!"
  gamemode:
    description: Change your game mode like before using numbers (or names)
    usage: /gamemode <0-3|name>
    permission: survivalutils.gamemode
    permission-message: "§cYou do not have permission to use this command!"
  craft:
    description: Opens a crafting table
    usage: /craft
    permission: survivalutils.workbench
    permission-message: "§cYou do not have permission to use this command!"

permissions:
  survivalutils.*:
    description: Grants access to all SurvivalUtils commands
    default: op
    children:
      survivalutils.feed: true
      survivalutils.heal: true
      survivalutils.repair: true
      survivalutils.gamemode: true
      survivalutils.craft: true